#+TITLE: Understanding and Predicting Property Maintenance Fines

* Introduction
You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [[https://www.coursera.org/learn/python-machine-learning/resources/bANLa][Jupyter Notebook FAQ]] course resource.

This assignment is based on a data challenge from the Michigan Data Science Team ([[http://midas.umich.edu/mdst/][MDST)]]. 

The Michigan Data Science Team ([[http://midas.umich.edu/mdst/][MDST]]) and the Michigan Student Symposium for Interdisciplinary Statistical Sciences ([[https://sites.lsa.umich.edu/mssiss/][MSSISS]]) have partnered with the City of Detroit to help solve one of the most pressing problems facing Detroit - blight. [[http://www.detroitmi.gov/How-Do-I/Report/Blight-Complaint-FAQs][Blight violations]] are issued by the city to individuals who allow their properties to remain in a deteriorated condition. Every year, the city of Detroit issues millions of dollars in fines to residents and every year, many of these fines remain unpaid. Enforcing unpaid blight fines is a costly and tedious process, so the city wants to know: how can we increase blight ticket compliance?

The first step in answering this question is understanding when and why a resident might fail to comply with a blight ticket. This is where predictive modeling comes in. For this assignment, your task is to predict whether a given blight ticket will be paid on time.

All data for this assignment has been provided to us through the [[https://data.detroitmi.gov/][Detroit Open Data Portal]]. **Only the data already included in your Coursera directory can be used for training the model for this assignment.** Nonetheless, we encourage you to look into data from other Detroit datasets to help inform feature creation and model selection. We recommend taking a look at the following related datasets:

 - [[https://data.detroitmi.gov/Property-Parcels/Building-Permits/xw2a-a7tf][Building Permits]]
 - [[https://data.detroitmi.gov/Property-Parcels/Trades-Permits/635b-dsgv][Trades Permits]]
 - [[https://data.detroitmi.gov/Government/Improve-Detroit-Submitted-Issues/fwz3-w3yn][Improve Detroit: Submitted Issues]]
 - [[https://data.detroitmi.gov/Public-Safety/DPD-Citizen-Complaints-2016/kahe-efs3][DPD: Citizen Complaints]]
 - [[https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwf][Parcel Map]]

We provide you with two data files for use in training and validating your models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

** File descriptions (Use only this data for training your model!)
 
     train.csv - the training set (all tickets issued 2004-2011)
     test.csv - the test set (all tickets issued 2012-2016)
     addresses.csv & latlons.csv - mapping from ticket id to addresses, and from addresses to lat/lon coordinates. 
      Note: misspelled addresses may be incorrectly geolocated.
 
** Data fields
*** train.csv & test.csv
 
    - ticket_id - unique identifier for tickets
    - agency_name - Agency that issued the ticket
    - inspector_name - Name of inspector that issued the ticket
    - violator_name - Name of the person/organization that the ticket was issued to
    - violation_street_number, violation_street_name, violation_zip_code - Address where the violation occurred
    - mailing_address_str_number, mailing_address_str_name, city, state, zip_code, non_us_str_code, country - Mailing address of the violator
    - ticket_issued_date - Date and time the ticket was issued
    - hearing_date - Date and time the violator's hearing was scheduled
    - violation_code, violation_description - Type of violation
    - disposition - Judgment and judgement type
    - fine_amount - Violation fine amount, excluding fees
    - admin_fee - $20 fee assigned to responsible judgments
    - state_fee - $10 fee assigned to responsible judgments
    - late_fee - 10% fee assigned to responsible judgments
    - discount_amount - discount applied, if any
    - clean_up_cost - DPW clean-up or graffiti removal cost
    - judgment_amount - Sum of all fines and fees
    - grafitti_status - Flag for graffiti violations
     
*** train.csv only

    - payment_amount - Amount paid, if any
    - payment_date - Date payment was made, if it was received
    - payment_status - Current payment status as of Feb 1 2017
    - balance_due - Fines and fees still owed
    - collection_status - Flag for payments in collections
    - compliance [target variable for prediction] 
      -  Null = Not responsible
      -  0 = Responsible, non-compliant
      -  1 = Responsible, compliant
    - compliance_detail - More information on why each ticket was marked compliant or non-compliant

** Evaluation

Your predictions will be given as the probability that the corresponding blight ticket will be paid on time.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC). 

Your grade will be based on the AUC score computed for your classifier. A model which with an AUROC of 0.7 passes this assignment, over 0.75 will receive full points.

For this assignment, create a function that trains a model to predict blight ticket compliance in Detroit using `train.csv`. Using this model, return a series of length 61001 with the data being the probability that each corresponding ticket from `test.csv` will be paid, and the index being the ticket_id.
 
*** Example:
#+BEGIN_EXAMPLE
     ticket_id
        284932    0.531842
        285362    0.401958
        285361    0.105928
        285338    0.018572
                  ...
        376499    0.208567
        376500    0.818759
        369851    0.018528
        Name: compliance, dtype: float32
#+END_EXAMPLE

* Imports

#+BEGIN_SRC ipython :session blight :results none
# pypi
from tabulate import tabulate
import pandas
import numpy

from sklearn.dummy import DummyClassifier
from sklearn.model_selection import GridSearchCV
#+END_SRC

* Constants

#+BEGIN_SRC ipython :session blight :results none
TARGET = "compliance"
COLUMNS = ["ticket_id",
           "agency_name",
           "inspector_name",
           "violator_name",
           "violation_street_number", "violation_street_name", "violation_zip_code",
           "mailing_address_str_number", "mailing_address_str_name", "city", "state", "zip_code", "non_us_str_code", "country",
           "ticket_issued_date",
           "hearing_date",
           "violation_code", "violation_description",
           "disposition",
           "fine_amount",
           "admin_fee",
           "state_fee",
           "late_fee",
           "discount_amount",
           "clean_up_cost",
           "judgment_amount",
           "grafitti_status",]
#+END_SRC

* Loading The Data
#+BEGIN_SRC ipython :session blight :results none
class DataSources(object):
    training_file = "train.csv"
    testing_file = "test.csv"
    addresses_file = "addresses.csv"
    training_frame = "training.pkl"
    testing_frame = "testing.pkl"    
#+END_SRC

#+BEGIN_SRC ipython :session blight :results none
if not os.path.isfile(DataSources.training_frame):
    training = pandas.read_csv(DataSources.training_file.value, encoding="latin1")
    training.to_pickle(DataSources.training_frame)
else:
    training = pandas.read_pickle(DataSources.training_frame)
#+END_SRC

#+BEGIN_SRC ipython :session blight :results none
x_train = training[COLUMNS]
y_train = training[[TARGET]]
#+END_SRC

#+BEGIN_SRC ipython :session blight
x_train.columns
#+END_SRC

#+RESULTS:
: Index(['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
:        'violation_street_number', 'violation_street_name',
:        'violation_zip_code', 'mailing_address_str_number',
:        'mailing_address_str_name', 'city', 'state', 'zip_code',
:        'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
:        'violation_code', 'violation_description', 'disposition', 'fine_amount',
:        'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
:        'clean_up_cost', 'judgment_amount', 'grafitti_status'],
:       dtype='object')

#+BEGIN_SRC ipython :session blight
training.head(n=1)
#+END_SRC

#+RESULTS:
#+begin_example
   ticket_id                                     agency_name   inspector_name  \
0      22056  Buildings, Safety Engineering & Env Department  Sims, Martinzie   

                       violator_name  violation_street_number  \
0  INVESTMENT INC., MIDWEST MORTGAGE                   2900.0   

  violation_street_name  violation_zip_code  mailing_address_str_number  \
0                 TYLER                 NaN                         3.0   

  mailing_address_str_name     city     ...     clean_up_cost judgment_amount  \
0                S. WICKER  CHICAGO     ...               0.0           305.0   

  payment_amount balance_due payment_date      payment_status  \
0            0.0       305.0          NaN  NO PAYMENT APPLIED   

  collection_status grafitti_status            compliance_detail  compliance  
0               NaN             NaN  non-compliant by no payment         0.0  

[1 rows x 34 columns]
#+end_example

#+BEGIN_SRC ipython :session blight :results output raw :exports both
print(tabulate(x_train.describe(), headers="keys", tablefmt="orgtbl"))
#+END_SRC

#+RESULTS:
|       | ticket_id | violation_street_number | violation_zip_code | mailing_address_str_number | fine_amount | admin_fee | state_fee | late_fee | discount_amount | clean_up_cost | judgment_amount |
|-------+-----------+-------------------------+--------------------+----------------------------+-------------+-----------+-----------+----------+-----------------+---------------+-----------------|
| count |    250306 |                  250306 |                  0 |                     246704 |      250305 |    250306 |    250306 |   250306 |          250306 |        250306 |          250306 |
| mean  |    152666 |                 10649.9 |                nan |                    9149.79 |     374.423 |   12.7748 |   6.38738 |  21.4945 |        0.125167 |             0 |         268.685 |
| std   |   77189.9 |                 31887.3 |                nan |                    36020.3 |     707.196 |   9.60734 |   4.80367 |  56.4643 |         3.43018 |             0 |         626.915 |
| min   |     18645 |                       0 |                nan |                          1 |           0 |         0 |         0 |        0 |               0 |             0 |               0 |
| 25%   |   86549.2 |                    4739 |                nan |                        544 |         200 |         0 |         0 |        0 |               0 |             0 |               0 |
| 50%   |    152598 |                   10244 |                nan |                       2456 |         250 |        20 |        10 |       10 |               0 |             0 |             140 |
| 75%   |    219889 |                   15760 |                nan |                    12927.2 |         250 |        20 |        10 |       25 |               0 |             0 |             305 |
| max   |    366178 |             1.41541e+07 |                nan |                5.11134e+06 |       10000 |        20 |        10 |     1000 |             350 |             0 |           11030 |


#+BEGIN_SRC ipython :session blight
y_train.compliance.value_counts()
#+END_SRC

#+RESULTS:
: 0.0    148283
: 1.0     11597
: Name: compliance, dtype: int64

#+BEGIN_SRC ipython :session blight :results output raw :exports both
print(tabulate(y_train.describe(), headers="keys", tablefmt="orgtbl"))
#+END_SRC

#+RESULTS:
|       | compliance |
|-------+------------|
| count |     159880 |
| mean  |  0.0725357 |
| std   |   0.259374 |
| min   |          0 |
| 25%   |          0 |
| 50%   |          0 |
| 75%   |          0 |
| max   |          1 |

* Blight Models
** Dummy Baseline
#+BEGIN_SRC ipython :session blight :results none
dummy_base = DummyClassifier()
param_grid = dict(strategy=("stratified", "most_frequent"))
dummy = GridSearchCV(dummy_base, param_grid)
#+END_SRC

The data has both strings and numbers which non-tree classifiers can't use.

#+BEGIN_SRC ipython :session bligt :results none
train_test_split = len(x_train)
combined = pandas.concat(objs=[x_train, x_test], axis=0)
with_dummies = pandas.get_dummies(combined)
x_train_encoded = with_dummies[:train_test_split]
x_test_encoded = with_dummies[train_test_split:]
#+END_SRC

#+BEGIN_SRC ipython :session blight :results none
dummy.fit(x_train, y_train)
#+END_SRC
* Submission Function
#+BEGIN_SRC ipython :session blight :results none
def blight_model():
    
    # Your code here
    
    return # Your answer here
#+END_SRC

