#+TITLE: Assignment 1

* Introduction
In this assignment, you'll be working with messy medical data and using regular expressions to extract relevant information from the data. 

Each line of the =dates.txt= file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:

 - 04/20/2009; 04/20/09; 4/20/09; 4/3/09
 - Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
 - 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
 - Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
 - Feb 2009; Sep 2009; Oct 2010
 - 6/2008; 12/2009
 - 2009; 2010
 
Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:

 -  Assume all dates in xx/xx/xx format are mm/dd/yy
 -  Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
 -  If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
 -  If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.
 
For example if the original series was this:

#+BEGIN_EXAMPLE
     0    1999
     1    2010
     2    1978
     3    2015
     4    1985
#+END_EXAMPLE

# Your function should return this:

#+BEGIN_EXAMPLE
     0    2
     1    4
     2    0
     3    1
     4    3
#+END_EXAMPLE

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.
 
*This function should return a Series of length 500 and dtype int.*
* Imports
#+BEGIN_SRC ipython :session assignment1 :results none
import pandas
#+END_SRC

* Loading The Data

#+BEGIN_SRC ipython :session assignment1
with open('dates.txt') as reader:
    data_string = reader.read()
    data = pandas.Series(data_string.splitlines())

data.head(10)
#+END_SRC

#+RESULTS:
#+begin_example
0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object
#+end_example

#+BEGIN_SRC ipython :session assignment1
data.describe()
#+END_SRC

#+RESULTS:
: count                                                   500
: unique                                                  500
: top       4-13-89 Communication with referring physician...
: freq                                                      1
: dtype: object

* The Grammar
#+BEGIN_SRC ipython :session assignment1 :results none
DIGIT = r"\d"
ONE_OR_TWO_DIGITS = DIGIT + r"{1,2}"
TWO_DIGITS = DIGIT + r"{2}"
FOUR_DIGITS = DIGIT + r"{4}"
GROUP = r"({})"
SLASH = r"/"
OR = r'|'

TWENTIETH_CENTURY = GROUP.format(SLASH.join([ONE_OR_TWO_DIGITS,
                                             ONE_OR_TWO_DIGITS,
                                             TWO_DIGITS]))
NUMERIC = GROUP.format(SLASH.join([ONE_OR_TWO_DIGITS,
                                   ONE_OR_TWO_DIGITS,
                                   FOUR_DIGITS]))
DATE = OR.join([NUMERIC, TWENTIETH_CENTURY])
#+END_SRC

#+BEGIN_SRC ipython :session assignment1 :results none
def twentieth_century(date):
    """adds a 19 to the year

    Args:
     date (re.Regex): Extracted date
    """
    month, day, year = date.group(1).split(SLASH)
    year = "19{}".format(year)
    return SLASH.join([month, day, year])
#+END_SRC

#+BEGIN_SRC ipython :session assignment1 :results none
def take_two(line):
    match = re.search(TWENTIETH_CENTURY, line)
    if match:
        return twentieth_century(match)
    return line
#+END_SRC

#+BEGIN_SRC ipython :session assignment1 :results output
found = data[data.str.contains(DATE)]
print(len(found))
print(found.head())

#+END_SRC

#+RESULTS:
: 121
: 0         03/25/93 Total time of visit (in minutes):\n
: 1                       6/18/85 Primary Care Doctor:\n
: 2    sshe plans to move as of 7/8/71 In-Home Servic...
: 3                7 on 9/27/75 Audit C Score Current:\n
: 4    2/6/96 sleep studyPain Treatment Pain Level (N...
: dtype: object

* The date_sorter Function

#+BEGIN_SRC ipython :session assignment1 :results none
def date_sorter():
    
    # Your code here
    
    return # Your answer here
#+END_SRC

